export const navData = [
  {
    name: "Trade signals",
    href: "/signals",
  },
  {
    name: "Bots",
    href: "/bot",
  },
  {
    name: "About",
    href: "/about",
  },
  {
    name: "Resources",
    href: "/resource",
  },
];

export const signals = [
  {
    // image:
    name: "Technical analysis signals",
    abbr: "TAS",
    description:
      "These signals are generated based on technical indicators such as moving averages, RSI (Relative Strength Index), MACD (Moving Average Convergence Divergence), Bollinger Bands",
  },
  {
    // image:
    name: "Market Sentiment Signals",
    abbr: "MSS",
    description:
      "Market sentiment signals assess the overall sentiment or mood of traders towards a particular asset or market.",
  },
  {
    // image:
    name: "Alogrithmic Signals",
    abbr: "ALS",
    description:
      "Algorithmic trading signals generated by automated trading systems or algorithms",
  },
];
